### ISSUE TITLE
Highlight of parenthesis and operators

### ISSUE THREAD

**Issue by FraMecca** [Sirsireesh/vim-dlang-extra-highlight#1]
Hi,
thanks a lot for the effort in providing the highlight, it is really needed.

Can you add the possibility to enable the optional highlights that are in the original definitions?
https://github.com/octol/vim-cpp-enhanced-highlight/blob/master/after/syntax/c.vim
(at the end, row 272)

**Comment by SirSireesh** [comment]
Thanks a lot for your kind words!

I added support for highlighting operators and delimiters, hidden behind the option d_optional_highlight. You can use it by adding
````vim
let g:d_optional_highlight = 1
````
to your vimrc. Is that fine?

**Comment by SirSireesh** [comment]
Closing the issue
